### ISSUE TITLE
Add support for PHP 8 - Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by seanBlommaert** [joshtronic/php-loremipsum#15]
Running the library I'm getting deprecation notices in PHP8.

   `Implicit conversion from float 22.003629414198972 to int loses precision`

For example in the sentences() method. The function `$this->gauss(24.46, 5.08)` returns a float while `$this->wordsArray()` expects an int.

  `$this->wordsArray($this->gauss(24.46, 5.08))`

Not sure if there are any other places that might throw errors?

**Comment by seanBlommaert** [comment]
So sorry, while trying to create a PR I see this has been fixed but I was just using an old version.

**Comment by xmontero** [comment]
What version was it fixed on?

**Comment by joshtronic** [comment]
> What version was it fixed on?

Introduced in 2.0.0, further improved (for 8.1) in 2.1.0, as per the release notes.
