### ISSUE TITLE
Feature Request: Specific min (and max?) character length when using word()

### ISSUE THREAD

**Issue by gmhenderson** [joshtronic/php-loremipsum#4]
It would be cool if there was some way to specify a minimum character length when using the `$lipsum->word()` method. I find I get 2- or 3-letter words too often. As for implementation, I'm not sure what would work best, since the second argument is already used for wrapping with HTML.

```
$lipsum->setMinChars(5)->word();
```
Maybe? Anyway, thanks for this really useful package, I use it all the time.

**Comment by joshtronic** [comment]
Thanks for reaching out, actually surprised to see a feature request for this particular project!

Yeah, doing something like that would probably be the best bet in terms of interfacing without breaking the current interfacing, although definitely wouldn't mind moving to using an args dictionary to allow for new options in the future (although, hard to imagine there being TOO many more options to add).

Will put this one on my list for the next week or so (leaving this open until it's done).

Cheers!

**Comment by joshtronic** [comment]
@gmhenderson I put some eyes on this one this evening, and after figuring out what the heck my code was doing, I'm thinking it's a bit more involved than expected.

My major caveat is that by being able to specify minimums (and/or maximums) and how the words are shuffled, you can screw yourself and end up with an infinite loop.

I don't think the suggestion is without merit, but with just the one request for it and the amount of work I can foresee with ensuring that those infinite loops are avoided, I'm going to put a pin in this one.

I'll leave the issue open for a while to see if it gets any upvotes or anything and if the need arises for a rewrite of this code in the future, I'll keep this suggestion on the list.

Suspect, you already found a solution to the problem yourself, but if not, I'd just go ahead and generate a bunch of words, filter the array by length and then slice that to get down to the number of words you need.

**Comment by gmhenderson** [comment]
@joshtronic totally fair. Thanks for taking some time to look into it.

**Comment by joshtronic** [comment]
Gonna close this one since nobody else chimed in with any interest.
